### ISSUE TITLE
[Feature/Tweak Suggestion] Void Fiend Tresspass ability dealing fall damage to self

### ISSUE THREAD

**Issue by BravoXray** [Moffein/RiskyTweaks#1]
I'm not sure how such a thing might be implemented, but I was curious if there might be any plans or motivation to do so.

As many are familiar, the uncorrupted version of Void Fiend's 'Tresspass' ability sends him upwards in an arc, and basically always hits you with some fall damage as you come back down, which breaks Safer Spaces or Opal's protection.

Would it be within the scope of this mod to adjust/remove that in some way? Either by giving Fiend resistance to fall damage for a few seconds after exiting Tresspass, or by reducing the height gained by a small margain? Perhaps another way I haven't thought of?

**Comment by Moffein** [comment]
Updated the mod.
I've moved RiskyMod's Trespass Height Scaling option to this mod since it's vanilla-compatible.
I'm not sure if fall immunity after Trespass would require syncing or not, so I won't be able to do that for the time being.
