### ISSUE TITLE
Moon pillars sometimes somehow ignoring config..?

### ISSUE THREAD

**Issue by inkyarev** [Moffein/RiskyTweaks#3]
![Screenshot 2024-10-16 003729](https://github.com/user-attachments/assets/6fc78ec5-5a62-4026-8721-f9710112b330)
![Screenshot 2024-10-16 004147](https://github.com/user-attachments/assets/5bce7f9c-b291-42f6-b14a-f35dbe8b957f)
seems to follow the config like half of the time
![Screenshot 2024-10-16 004427](https://github.com/user-attachments/assets/1d88016c-a41b-42e2-bb5a-34aa43e9def0)

**Comment by Moffein** [comment]
Thanks for reporting this. I've found the issue and uploaded a fix.
